modes:  # 选择网络、损失函数，是否训练
    method: 'Transformer_puredemod'
    path: 'best'
    loss: 'loss_cos' # 使用'loss_CE_and_MSE'会报错，
    optimizer: 'adamw' # 'adamw' or 'sgd'
    load_pretrained: True
    load_pretrained_path: './results\Transformer_puredemod\best\ours\checkpoints\best_CQ_150epoch.pth'
    load_pretrained_pos: False
    train: True
    ddp: False
data_settings:  # 数据读取载入方式，用于设置data_loader
    dataset: 'ours' #我们要使用自己定义的数据集
    Xmode:
        type: 'iq'
        options:
            IQ_norm: False  # 归一化到[0, 1]
            zero_mask: False
            random_mix: False
    mod_type: [ 'BPSK', 'QPSK', '8PSK', 'MSK', '8QAM', '16QAM', '32QAM', '8APSK', '16APSK', '32APSK','others']
opt_params:  # 网络训练参数
    batch_size: 512
    epochs: 150
    lr: 6e-4
    workers: 8
    seed: 1
    gpu: 0
    cpu: False
    early_stop: False